name: My workflow

on: push

jobs:
  CI:
    name: Teste de CI  
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '23.x'
    - name: Instalar dependências
      run: npm install
    - name: Executar testes
      run: npm run test
    - name: Gerar build
      run: npm run build
    - name: Listar diretório
      run: ls -la .
      
  CD:
    needs: CI
    name: Teste de CD 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install surge and fire deployment
        uses: actions/setup-node@v3
        with:
          node-version: '23.x'
      - name: Listar diretório
        run: ls -la .
      - run: npm install -g surge
      - run: surge ./dist ilson-filho.surge.sh --token 36765332d5b02e992f32f2678f151539